//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 02:53:36 PM IST 
//


package com.sho.renaissance.batch.cif;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.sho.renaissance.batch.cif.ProcessActivityBatchType;
import com.sho.renaissance.batch.cif.ProcessActivityDetailType;
import com.sho.renaissance.batch.cif.ProcessActivityHeaderType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processActivityHeader" type="{http://com.capgemini/cif}ProcessActivityHeaderType"/>
 *         &lt;element name="processActivityBatch" type="{http://com.capgemini/cif/dim}ProcessActivityBatchType" minOccurs="0"/>
 *         &lt;element name="processActivityDetailList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="processActivityDetail" type="{http://com.capgemini/cif/dim}ProcessActivityDetailType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processActivityHeader",
    "processActivityBatch",
    "processActivityDetailList"
})
@XmlRootElement(name = "LogProcessActivityRequest", namespace = "http://com.capgemini/cif/dim")
public class LogProcessActivityRequest {

    @XmlElement(namespace = "http://com.capgemini/cif/dim", required = true)
    protected ProcessActivityHeaderType processActivityHeader;
    @XmlElement(namespace = "http://com.capgemini/cif/dim")
    protected ProcessActivityBatchType processActivityBatch;
    @XmlElement(namespace = "http://com.capgemini/cif/dim")
    protected LogProcessActivityRequest.ProcessActivityDetailList processActivityDetailList;

    /**
     * Gets the value of the processActivityHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessActivityHeaderType }
     *     
     */
    public ProcessActivityHeaderType getProcessActivityHeader() {
        return processActivityHeader;
    }

    /**
     * Sets the value of the processActivityHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessActivityHeaderType }
     *     
     */
    public void setProcessActivityHeader(ProcessActivityHeaderType value) {
        this.processActivityHeader = value;
    }

    /**
     * Gets the value of the processActivityBatch property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessActivityBatchType }
     *     
     */
    public ProcessActivityBatchType getProcessActivityBatch() {
        return processActivityBatch;
    }

    /**
     * Sets the value of the processActivityBatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessActivityBatchType }
     *     
     */
    public void setProcessActivityBatch(ProcessActivityBatchType value) {
        this.processActivityBatch = value;
    }

    /**
     * Gets the value of the processActivityDetailList property.
     * 
     * @return
     *     possible object is
     *     {@link LogProcessActivityRequest.ProcessActivityDetailList }
     *     
     */
    public LogProcessActivityRequest.ProcessActivityDetailList getProcessActivityDetailList() {
        return processActivityDetailList;
    }

    /**
     * Sets the value of the processActivityDetailList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogProcessActivityRequest.ProcessActivityDetailList }
     *     
     */
    public void setProcessActivityDetailList(LogProcessActivityRequest.ProcessActivityDetailList value) {
        this.processActivityDetailList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="processActivityDetail" type="{http://com.capgemini/cif/dim}ProcessActivityDetailType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "processActivityDetail"
    })
    public static class ProcessActivityDetailList {

        @XmlElement(namespace = "http://com.capgemini/cif/dim", required = true)
        protected List<ProcessActivityDetailType> processActivityDetail;

        /**
         * Gets the value of the processActivityDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the processActivityDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcessActivityDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProcessActivityDetailType }
         * 
         * 
         */
        public List<ProcessActivityDetailType> getProcessActivityDetail() {
            if (processActivityDetail == null) {
                processActivityDetail = new ArrayList<ProcessActivityDetailType>();
            }
            return this.processActivityDetail;
        }

    }

}
