//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 02:53:36 PM IST 
//


package com.sho.renaissance.batch.cif;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProcessActivityBatchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessActivityBatchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processStartDatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recordCount" type="{http://com.capgemini/cif}CountType"/>
 *         &lt;element name="processCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="processValue" type="{http://com.capgemini/cif}ValueType" minOccurs="0"/>
 *         &lt;element name="filterRecordCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="filterProcessCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="filterProcessValue" type="{http://com.capgemini/cif}ValueType" minOccurs="0"/>
 *         &lt;element name="processedRecordCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="processedProcessCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="processedProcessValue" type="{http://com.capgemini/cif}ValueType" minOccurs="0"/>
 *         &lt;element name="errorRecordCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="errorProcessCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="errorProcessValue" type="{http://com.capgemini/cif}ValueType" minOccurs="0"/>
 *         &lt;element name="unprocessedRecordCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="unprocessedProcessCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="unprocessedProcessValue" type="{http://com.capgemini/cif}ValueType" minOccurs="0"/>
 *         &lt;element name="statusId" type="{http://com.capgemini/cif}IdType"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessActivityBatchType", namespace = "http://com.capgemini/cif/dim", propOrder = {
    "processStartDatetime",
    "fileName",
    "recordCount",
    "processCount",
    "processValue",
    "filterRecordCount",
    "filterProcessCount",
    "filterProcessValue",
    "processedRecordCount",
    "processedProcessCount",
    "processedProcessValue",
    "errorRecordCount",
    "errorProcessCount",
    "errorProcessValue",
    "unprocessedRecordCount",
    "unprocessedProcessCount",
    "unprocessedProcessValue",
    "statusId",
    "comment"
})
public class ProcessActivityBatchType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar processStartDatetime;
    protected String fileName;
    protected int recordCount;
    @XmlElement(defaultValue = "0")
    protected Integer processCount;
    @XmlElement(defaultValue = "0")
    protected BigDecimal processValue;
    @XmlElement(defaultValue = "0")
    protected Integer filterRecordCount;
    @XmlElement(defaultValue = "0")
    protected Integer filterProcessCount;
    @XmlElement(defaultValue = "0")
    protected BigDecimal filterProcessValue;
    @XmlElement(defaultValue = "0")
    protected Integer processedRecordCount;
    @XmlElement(defaultValue = "0")
    protected Integer processedProcessCount;
    @XmlElement(defaultValue = "0")
    protected BigDecimal processedProcessValue;
    @XmlElement(defaultValue = "0")
    protected Integer errorRecordCount;
    @XmlElement(defaultValue = "0")
    protected Integer errorProcessCount;
    @XmlElement(defaultValue = "0")
    protected BigDecimal errorProcessValue;
    @XmlElement(defaultValue = "0")
    protected Integer unprocessedRecordCount;
    @XmlElement(defaultValue = "0")
    protected Integer unprocessedProcessCount;
    @XmlElement(defaultValue = "0")
    protected BigDecimal unprocessedProcessValue;
    @XmlElement(required = true)
    protected String statusId;
    protected String comment;

    /**
     * Gets the value of the processStartDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessStartDatetime() {
        return processStartDatetime;
    }

    /**
     * Sets the value of the processStartDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessStartDatetime(XMLGregorianCalendar value) {
        this.processStartDatetime = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the recordCount property.
     * 
     */
    public int getRecordCount() {
        return recordCount;
    }

    /**
     * Sets the value of the recordCount property.
     * 
     */
    public void setRecordCount(int value) {
        this.recordCount = value;
    }

    /**
     * Gets the value of the processCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProcessCount() {
        return processCount;
    }

    /**
     * Sets the value of the processCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProcessCount(Integer value) {
        this.processCount = value;
    }

    /**
     * Gets the value of the processValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProcessValue() {
        return processValue;
    }

    /**
     * Sets the value of the processValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProcessValue(BigDecimal value) {
        this.processValue = value;
    }

    /**
     * Gets the value of the filterRecordCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFilterRecordCount() {
        return filterRecordCount;
    }

    /**
     * Sets the value of the filterRecordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFilterRecordCount(Integer value) {
        this.filterRecordCount = value;
    }

    /**
     * Gets the value of the filterProcessCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFilterProcessCount() {
        return filterProcessCount;
    }

    /**
     * Sets the value of the filterProcessCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFilterProcessCount(Integer value) {
        this.filterProcessCount = value;
    }

    /**
     * Gets the value of the filterProcessValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFilterProcessValue() {
        return filterProcessValue;
    }

    /**
     * Sets the value of the filterProcessValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFilterProcessValue(BigDecimal value) {
        this.filterProcessValue = value;
    }

    /**
     * Gets the value of the processedRecordCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProcessedRecordCount() {
        return processedRecordCount;
    }

    /**
     * Sets the value of the processedRecordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProcessedRecordCount(Integer value) {
        this.processedRecordCount = value;
    }

    /**
     * Gets the value of the processedProcessCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProcessedProcessCount() {
        return processedProcessCount;
    }

    /**
     * Sets the value of the processedProcessCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProcessedProcessCount(Integer value) {
        this.processedProcessCount = value;
    }

    /**
     * Gets the value of the processedProcessValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProcessedProcessValue() {
        return processedProcessValue;
    }

    /**
     * Sets the value of the processedProcessValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProcessedProcessValue(BigDecimal value) {
        this.processedProcessValue = value;
    }

    /**
     * Gets the value of the errorRecordCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getErrorRecordCount() {
        return errorRecordCount;
    }

    /**
     * Sets the value of the errorRecordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setErrorRecordCount(Integer value) {
        this.errorRecordCount = value;
    }

    /**
     * Gets the value of the errorProcessCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getErrorProcessCount() {
        return errorProcessCount;
    }

    /**
     * Sets the value of the errorProcessCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setErrorProcessCount(Integer value) {
        this.errorProcessCount = value;
    }

    /**
     * Gets the value of the errorProcessValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getErrorProcessValue() {
        return errorProcessValue;
    }

    /**
     * Sets the value of the errorProcessValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setErrorProcessValue(BigDecimal value) {
        this.errorProcessValue = value;
    }

    /**
     * Gets the value of the unprocessedRecordCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUnprocessedRecordCount() {
        return unprocessedRecordCount;
    }

    /**
     * Sets the value of the unprocessedRecordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUnprocessedRecordCount(Integer value) {
        this.unprocessedRecordCount = value;
    }

    /**
     * Gets the value of the unprocessedProcessCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUnprocessedProcessCount() {
        return unprocessedProcessCount;
    }

    /**
     * Sets the value of the unprocessedProcessCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUnprocessedProcessCount(Integer value) {
        this.unprocessedProcessCount = value;
    }

    /**
     * Gets the value of the unprocessedProcessValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnprocessedProcessValue() {
        return unprocessedProcessValue;
    }

    /**
     * Sets the value of the unprocessedProcessValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnprocessedProcessValue(BigDecimal value) {
        this.unprocessedProcessValue = value;
    }

    /**
     * Gets the value of the statusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * Sets the value of the statusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusId(String value) {
        this.statusId = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
