//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 02:53:36 PM IST 
//


package com.sho.renaissance.batch.cif;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.sho.renaissance.batch.cif.ProcessActivityPayloadType;


/**
 * <p>Java class for ProcessActivityDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessActivityDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processSequence" type="{http://com.capgemini/cif}CountType"/>
 *         &lt;element name="processIndex" type="{http://com.capgemini/cif}CountType"/>
 *         &lt;element name="processDatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="sourceSystemReference" type="{http://com.capgemini/cif}ReferenceIdType" minOccurs="0"/>
 *         &lt;element name="destinationSystemReference" type="{http://com.capgemini/cif}ReferenceIdType" minOccurs="0"/>
 *         &lt;element name="recordCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="recordValue" type="{http://com.capgemini/cif}ValueType" minOccurs="0"/>
 *         &lt;element name="errorCount" type="{http://com.capgemini/cif}CountType" minOccurs="0"/>
 *         &lt;element name="errorValue" type="{http://com.capgemini/cif}ValueType" minOccurs="0"/>
 *         &lt;element name="statusId" type="{http://com.capgemini/cif}IdType"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="processActivityPayload" type="{http://com.capgemini/cif/dim}ProcessActivityPayloadType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessActivityDetailType", namespace = "http://com.capgemini/cif/dim", propOrder = {
    "processSequence",
    "processIndex",
    "processDatetime",
    "sourceSystemReference",
    "destinationSystemReference",
    "recordCount",
    "recordValue",
    "errorCount",
    "errorValue",
    "statusId",
    "comment",
    "processActivityPayload"
})
public class ProcessActivityDetailType {

    @XmlElement(defaultValue = "0")
    protected int processSequence;
    @XmlElement(defaultValue = "0")
    protected int processIndex;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar processDatetime;
    protected String sourceSystemReference;
    protected String destinationSystemReference;
    @XmlElement(defaultValue = "0")
    protected Integer recordCount;
    @XmlElement(defaultValue = "0")
    protected BigDecimal recordValue;
    @XmlElement(defaultValue = "0")
    protected Integer errorCount;
    @XmlElement(defaultValue = "0")
    protected BigDecimal errorValue;
    @XmlElement(required = true)
    protected String statusId;
    protected String comment;
    protected ProcessActivityPayloadType processActivityPayload;

    /**
     * Gets the value of the processSequence property.
     * 
     */
    public int getProcessSequence() {
        return processSequence;
    }

    /**
     * Sets the value of the processSequence property.
     * 
     */
    public void setProcessSequence(int value) {
        this.processSequence = value;
    }

    /**
     * Gets the value of the processIndex property.
     * 
     */
    public int getProcessIndex() {
        return processIndex;
    }

    /**
     * Sets the value of the processIndex property.
     * 
     */
    public void setProcessIndex(int value) {
        this.processIndex = value;
    }

    /**
     * Gets the value of the processDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessDatetime() {
        return processDatetime;
    }

    /**
     * Sets the value of the processDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessDatetime(XMLGregorianCalendar value) {
        this.processDatetime = value;
    }

    /**
     * Gets the value of the sourceSystemReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceSystemReference() {
        return sourceSystemReference;
    }

    /**
     * Sets the value of the sourceSystemReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceSystemReference(String value) {
        this.sourceSystemReference = value;
    }

    /**
     * Gets the value of the destinationSystemReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationSystemReference() {
        return destinationSystemReference;
    }

    /**
     * Sets the value of the destinationSystemReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationSystemReference(String value) {
        this.destinationSystemReference = value;
    }

    /**
     * Gets the value of the recordCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecordCount() {
        return recordCount;
    }

    /**
     * Sets the value of the recordCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecordCount(Integer value) {
        this.recordCount = value;
    }

    /**
     * Gets the value of the recordValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRecordValue() {
        return recordValue;
    }

    /**
     * Sets the value of the recordValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRecordValue(BigDecimal value) {
        this.recordValue = value;
    }

    /**
     * Gets the value of the errorCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getErrorCount() {
        return errorCount;
    }

    /**
     * Sets the value of the errorCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setErrorCount(Integer value) {
        this.errorCount = value;
    }

    /**
     * Gets the value of the errorValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getErrorValue() {
        return errorValue;
    }

    /**
     * Sets the value of the errorValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setErrorValue(BigDecimal value) {
        this.errorValue = value;
    }

    /**
     * Gets the value of the statusId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * Sets the value of the statusId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusId(String value) {
        this.statusId = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the processActivityPayload property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessActivityPayloadType }
     *     
     */
    public ProcessActivityPayloadType getProcessActivityPayload() {
        return processActivityPayload;
    }

    /**
     * Sets the value of the processActivityPayload property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessActivityPayloadType }
     *     
     */
    public void setProcessActivityPayload(ProcessActivityPayloadType value) {
        this.processActivityPayload = value;
    }

}
