//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 02:19:50 PM IST 
//


package com.concretepage.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="token" type="{http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model}AuthenticationToken" minOccurs="0"/&gt;
 *         &lt;element name="auditReceipt" type="{http://schemas.microsoft.com/2003/10/Serialization/}guid" minOccurs="0"/&gt;
 *         &lt;element name="rowIdList" type="{http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfstring" minOccurs="0"/&gt;
 *         &lt;element name="receiptDetails" type="{http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model}ReceiptDetails" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "token",
    "auditReceipt",
    "rowIdList",
    "receiptDetails"
})
@XmlRootElement(name = "GetReceiptDetails")
public class GetReceiptDetails {

    @XmlElementRef(name = "token", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<AuthenticationToken> token;
    protected String auditReceipt;
    @XmlElementRef(name = "rowIdList", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfstring> rowIdList;
    @XmlElementRef(name = "receiptDetails", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<ReceiptDetails> receiptDetails;

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}
     *     
     */
    public JAXBElement<AuthenticationToken> getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}
     *     
     */
    public void setToken(JAXBElement<AuthenticationToken> value) {
        this.token = value;
    }

    /**
     * Gets the value of the auditReceipt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditReceipt() {
        return auditReceipt;
    }

    /**
     * Sets the value of the auditReceipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditReceipt(String value) {
        this.auditReceipt = value;
    }

    /**
     * Gets the value of the rowIdList property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfstring }{@code >}
     *     
     */
    public JAXBElement<ArrayOfstring> getRowIdList() {
        return rowIdList;
    }

    /**
     * Sets the value of the rowIdList property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfstring }{@code >}
     *     
     */
    public void setRowIdList(JAXBElement<ArrayOfstring> value) {
        this.rowIdList = value;
    }

    /**
     * Gets the value of the receiptDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ReceiptDetails }{@code >}
     *     
     */
    public JAXBElement<ReceiptDetails> getReceiptDetails() {
        return receiptDetails;
    }

    /**
     * Sets the value of the receiptDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ReceiptDetails }{@code >}
     *     
     */
    public void setReceiptDetails(JAXBElement<ReceiptDetails> value) {
        this.receiptDetails = value;
    }

}
