//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 02:19:50 PM IST 
//


package com.concretepage.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ImportExportDataResult" type="{http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model}ArrayOfResult" minOccurs="0"/&gt;
 *         &lt;element name="importExportInstruction" type="{http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model}Instruction" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "importExportDataResult",
    "importExportInstruction"
})
@XmlRootElement(name = "ImportExportDataResponse")
public class ImportExportDataResponse {

    @XmlElementRef(name = "ImportExportDataResult", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfResult> importExportDataResult;
    @XmlElementRef(name = "importExportInstruction", namespace = "http://tempuri.org/", type = JAXBElement.class, required = false)
    protected JAXBElement<Instruction> importExportInstruction;

    /**
     * Gets the value of the importExportDataResult property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}
     *     
     */
    public JAXBElement<ArrayOfResult> getImportExportDataResult() {
        return importExportDataResult;
    }

    /**
     * Sets the value of the importExportDataResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}
     *     
     */
    public void setImportExportDataResult(JAXBElement<ArrayOfResult> value) {
        this.importExportDataResult = value;
    }

    /**
     * Gets the value of the importExportInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Instruction }{@code >}
     *     
     */
    public JAXBElement<Instruction> getImportExportInstruction() {
        return importExportInstruction;
    }

    /**
     * Sets the value of the importExportInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Instruction }{@code >}
     *     
     */
    public void setImportExportInstruction(JAXBElement<Instruction> value) {
        this.importExportInstruction = value;
    }

}
