//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 02:19:50 PM IST 
//


package com.concretepage.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Instruction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Instruction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Directive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Payload" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PayloadType" type="{http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Enums}EnumPayloadType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Instruction", namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", propOrder = {
    "directive",
    "payload",
    "payloadType"
})
public class Instruction {

    @XmlElementRef(name = "Directive", namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", type = JAXBElement.class, required = false)
    protected JAXBElement<String> directive;
    @XmlElementRef(name = "Payload", namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", type = JAXBElement.class, required = false)
    protected JAXBElement<String> payload;
    @XmlElement(name = "PayloadType")
    @XmlSchemaType(name = "string")
    protected EnumPayloadType payloadType;

    /**
     * Gets the value of the directive property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDirective() {
        return directive;
    }

    /**
     * Sets the value of the directive property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDirective(JAXBElement<String> value) {
        this.directive = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPayload(JAXBElement<String> value) {
        this.payload = value;
    }

    /**
     * Gets the value of the payloadType property.
     * 
     * @return
     *     possible object is
     *     {@link EnumPayloadType }
     *     
     */
    public EnumPayloadType getPayloadType() {
        return payloadType;
    }

    /**
     * Sets the value of the payloadType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumPayloadType }
     *     
     */
    public void setPayloadType(EnumPayloadType value) {
        this.payloadType = value;
    }

}
