//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 02:19:50 PM IST 
//


package com.concretepage.wsdl;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.concretepage.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AuthenticationToken_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "AuthenticationToken");
    private final static QName _ArrayOfResult_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "ArrayOfResult");
    private final static QName _Result_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "Result");
    private final static QName _Instruction_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "Instruction");
    private final static QName _ReceiptSummary_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "ReceiptSummary");
    private final static QName _ArrayOfSummaryRowData_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "ArrayOfSummaryRowData");
    private final static QName _SummaryRowData_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "SummaryRowData");
    private final static QName _ReceiptDetails_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "ReceiptDetails");
    private final static QName _AnyType_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyType");
    private final static QName _AnyURI_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "anyURI");
    private final static QName _Base64Binary_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "base64Binary");
    private final static QName _Boolean_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "boolean");
    private final static QName _Byte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "byte");
    private final static QName _DateTime_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "dateTime");
    private final static QName _Decimal_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "decimal");
    private final static QName _Double_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "double");
    private final static QName _Float_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "float");
    private final static QName _Int_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "int");
    private final static QName _Long_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "long");
    private final static QName _QName_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "QName");
    private final static QName _Short_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "short");
    private final static QName _String_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "string");
    private final static QName _UnsignedByte_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedByte");
    private final static QName _UnsignedInt_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedInt");
    private final static QName _UnsignedLong_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedLong");
    private final static QName _UnsignedShort_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "unsignedShort");
    private final static QName _Char_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "char");
    private final static QName _Duration_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "duration");
    private final static QName _Guid_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/", "guid");
    private final static QName _EnumPayloadType_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Enums", "EnumPayloadType");
    private final static QName _ArrayOfstring_QNAME = new QName("http://schemas.microsoft.com/2003/10/Serialization/Arrays", "ArrayOfstring");
    private final static QName _AuthenticateUserUsername_QNAME = new QName("http://tempuri.org/", "username");
    private final static QName _AuthenticateUserPassword_QNAME = new QName("http://tempuri.org/", "password");
    private final static QName _AuthenticateUserCompany_QNAME = new QName("http://tempuri.org/", "company");
    private final static QName _AuthenticateUserToken_QNAME = new QName("http://tempuri.org/", "token");
    private final static QName _AuthenticateUserResponseAuthenticateUserResult_QNAME = new QName("http://tempuri.org/", "AuthenticateUserResult");
    private final static QName _BeginBatchBatchId_QNAME = new QName("http://tempuri.org/", "batchId");
    private final static QName _BeginBatchResponseBeginBatchResult_QNAME = new QName("http://tempuri.org/", "BeginBatchResult");
    private final static QName _ImportDataImportInstruction_QNAME = new QName("http://tempuri.org/", "importInstruction");
    private final static QName _ImportDataResponseImportDataResult_QNAME = new QName("http://tempuri.org/", "ImportDataResult");
    private final static QName _ExportDataExportInstruction_QNAME = new QName("http://tempuri.org/", "exportInstruction");
    private final static QName _ExportDataResponseExportDataResult_QNAME = new QName("http://tempuri.org/", "ExportDataResult");
    private final static QName _ImportExportDataImportExportInstruction_QNAME = new QName("http://tempuri.org/", "importExportInstruction");
    private final static QName _ImportExportDataResponseImportExportDataResult_QNAME = new QName("http://tempuri.org/", "ImportExportDataResult");
    private final static QName _EndBatchResponseEndBatchResult_QNAME = new QName("http://tempuri.org/", "EndBatchResult");
    private final static QName _GetReceiptSummaryWithBatchIDReceiptSummary_QNAME = new QName("http://tempuri.org/", "receiptSummary");
    private final static QName _GetReceiptSummaryWithBatchIDResponseGetReceiptSummaryWithBatchIDResult_QNAME = new QName("http://tempuri.org/", "GetReceiptSummaryWithBatchIDResult");
    private final static QName _GetReceiptSummaryWithAuditReceiptResponseGetReceiptSummaryWithAuditReceiptResult_QNAME = new QName("http://tempuri.org/", "GetReceiptSummaryWithAuditReceiptResult");
    private final static QName _GetReceiptDetailsRowIdList_QNAME = new QName("http://tempuri.org/", "rowIdList");
    private final static QName _GetReceiptDetailsReceiptDetails_QNAME = new QName("http://tempuri.org/", "receiptDetails");
    private final static QName _GetReceiptDetailsResponseGetReceiptDetailsResult_QNAME = new QName("http://tempuri.org/", "GetReceiptDetailsResult");
    private final static QName _SummaryRowDataBatchID_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "BatchID");
    private final static QName _SummaryRowDataExtraErrorDetails_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "ExtraErrorDetails");
    private final static QName _SummaryRowDataRowID_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "RowID");
    private final static QName _ResultMessage_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "Message");
    private final static QName _ResultSeverity_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "Severity");
    private final static QName _ResultStatusCode_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "StatusCode");
    private final static QName _ReceiptDetailsResultDetails_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "ResultDetails");
    private final static QName _ReceiptSummaryRowDataItems_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "RowDataItems");
    private final static QName _InstructionDirective_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "Directive");
    private final static QName _InstructionPayload_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "Payload");
    private final static QName _AuthenticationTokenBLL_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "BLL");
    private final static QName _AuthenticationTokenCompany_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "Company");
    private final static QName _AuthenticationTokenDAL_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "DAL");
    private final static QName _AuthenticationTokenSession_QNAME = new QName("http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", "Session");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.concretepage.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthenticateUser }
     * 
     */
    public AuthenticateUser createAuthenticateUser() {
        return new AuthenticateUser();
    }

    /**
     * Create an instance of {@link AuthenticationToken }
     * 
     */
    public AuthenticationToken createAuthenticationToken() {
        return new AuthenticationToken();
    }

    /**
     * Create an instance of {@link AuthenticateUserResponse }
     * 
     */
    public AuthenticateUserResponse createAuthenticateUserResponse() {
        return new AuthenticateUserResponse();
    }

    /**
     * Create an instance of {@link ArrayOfResult }
     * 
     */
    public ArrayOfResult createArrayOfResult() {
        return new ArrayOfResult();
    }

    /**
     * Create an instance of {@link BeginBatch }
     * 
     */
    public BeginBatch createBeginBatch() {
        return new BeginBatch();
    }

    /**
     * Create an instance of {@link BeginBatchResponse }
     * 
     */
    public BeginBatchResponse createBeginBatchResponse() {
        return new BeginBatchResponse();
    }

    /**
     * Create an instance of {@link ImportData }
     * 
     */
    public ImportData createImportData() {
        return new ImportData();
    }

    /**
     * Create an instance of {@link Instruction }
     * 
     */
    public Instruction createInstruction() {
        return new Instruction();
    }

    /**
     * Create an instance of {@link ImportDataResponse }
     * 
     */
    public ImportDataResponse createImportDataResponse() {
        return new ImportDataResponse();
    }

    /**
     * Create an instance of {@link ExportData }
     * 
     */
    public ExportData createExportData() {
        return new ExportData();
    }

    /**
     * Create an instance of {@link ExportDataResponse }
     * 
     */
    public ExportDataResponse createExportDataResponse() {
        return new ExportDataResponse();
    }

    /**
     * Create an instance of {@link ImportExportData }
     * 
     */
    public ImportExportData createImportExportData() {
        return new ImportExportData();
    }

    /**
     * Create an instance of {@link ImportExportDataResponse }
     * 
     */
    public ImportExportDataResponse createImportExportDataResponse() {
        return new ImportExportDataResponse();
    }

    /**
     * Create an instance of {@link EndBatch }
     * 
     */
    public EndBatch createEndBatch() {
        return new EndBatch();
    }

    /**
     * Create an instance of {@link EndBatchResponse }
     * 
     */
    public EndBatchResponse createEndBatchResponse() {
        return new EndBatchResponse();
    }

    /**
     * Create an instance of {@link GetReceiptSummaryWithBatchID }
     * 
     */
    public GetReceiptSummaryWithBatchID createGetReceiptSummaryWithBatchID() {
        return new GetReceiptSummaryWithBatchID();
    }

    /**
     * Create an instance of {@link ReceiptSummary }
     * 
     */
    public ReceiptSummary createReceiptSummary() {
        return new ReceiptSummary();
    }

    /**
     * Create an instance of {@link GetReceiptSummaryWithBatchIDResponse }
     * 
     */
    public GetReceiptSummaryWithBatchIDResponse createGetReceiptSummaryWithBatchIDResponse() {
        return new GetReceiptSummaryWithBatchIDResponse();
    }

    /**
     * Create an instance of {@link GetReceiptSummaryWithAuditReceipt }
     * 
     */
    public GetReceiptSummaryWithAuditReceipt createGetReceiptSummaryWithAuditReceipt() {
        return new GetReceiptSummaryWithAuditReceipt();
    }

    /**
     * Create an instance of {@link GetReceiptSummaryWithAuditReceiptResponse }
     * 
     */
    public GetReceiptSummaryWithAuditReceiptResponse createGetReceiptSummaryWithAuditReceiptResponse() {
        return new GetReceiptSummaryWithAuditReceiptResponse();
    }

    /**
     * Create an instance of {@link GetReceiptDetails }
     * 
     */
    public GetReceiptDetails createGetReceiptDetails() {
        return new GetReceiptDetails();
    }

    /**
     * Create an instance of {@link ArrayOfstring }
     * 
     */
    public ArrayOfstring createArrayOfstring() {
        return new ArrayOfstring();
    }

    /**
     * Create an instance of {@link ReceiptDetails }
     * 
     */
    public ReceiptDetails createReceiptDetails() {
        return new ReceiptDetails();
    }

    /**
     * Create an instance of {@link GetReceiptDetailsResponse }
     * 
     */
    public GetReceiptDetailsResponse createGetReceiptDetailsResponse() {
        return new GetReceiptDetailsResponse();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link ArrayOfSummaryRowData }
     * 
     */
    public ArrayOfSummaryRowData createArrayOfSummaryRowData() {
        return new ArrayOfSummaryRowData();
    }

    /**
     * Create an instance of {@link SummaryRowData }
     * 
     */
    public SummaryRowData createSummaryRowData() {
        return new SummaryRowData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "AuthenticationToken")
    public JAXBElement<AuthenticationToken> createAuthenticationToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticationToken_QNAME, AuthenticationToken.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "ArrayOfResult")
    public JAXBElement<ArrayOfResult> createArrayOfResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_ArrayOfResult_QNAME, ArrayOfResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Result }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Result")
    public JAXBElement<Result> createResult(Result value) {
        return new JAXBElement<Result>(_Result_QNAME, Result.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Instruction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Instruction")
    public JAXBElement<Instruction> createInstruction(Instruction value) {
        return new JAXBElement<Instruction>(_Instruction_QNAME, Instruction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "ReceiptSummary")
    public JAXBElement<ReceiptSummary> createReceiptSummary(ReceiptSummary value) {
        return new JAXBElement<ReceiptSummary>(_ReceiptSummary_QNAME, ReceiptSummary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfSummaryRowData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "ArrayOfSummaryRowData")
    public JAXBElement<ArrayOfSummaryRowData> createArrayOfSummaryRowData(ArrayOfSummaryRowData value) {
        return new JAXBElement<ArrayOfSummaryRowData>(_ArrayOfSummaryRowData_QNAME, ArrayOfSummaryRowData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SummaryRowData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "SummaryRowData")
    public JAXBElement<SummaryRowData> createSummaryRowData(SummaryRowData value) {
        return new JAXBElement<SummaryRowData>(_SummaryRowData_QNAME, SummaryRowData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "ReceiptDetails")
    public JAXBElement<ReceiptDetails> createReceiptDetails(ReceiptDetails value) {
        return new JAXBElement<ReceiptDetails>(_ReceiptDetails_QNAME, ReceiptDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyType")
    public JAXBElement<Object> createAnyType(Object value) {
        return new JAXBElement<Object>(_AnyType_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "anyURI")
    public JAXBElement<String> createAnyURI(String value) {
        return new JAXBElement<String>(_AnyURI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "base64Binary")
    public JAXBElement<byte[]> createBase64Binary(byte[] value) {
        return new JAXBElement<byte[]>(_Base64Binary_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "boolean")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "byte")
    public JAXBElement<Byte> createByte(Byte value) {
        return new JAXBElement<Byte>(_Byte_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "dateTime")
    public JAXBElement<XMLGregorianCalendar> createDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "decimal")
    public JAXBElement<BigDecimal> createDecimal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Decimal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "double")
    public JAXBElement<Double> createDouble(Double value) {
        return new JAXBElement<Double>(_Double_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "float")
    public JAXBElement<Float> createFloat(Float value) {
        return new JAXBElement<Float>(_Float_QNAME, Float.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "int")
    public JAXBElement<Integer> createInt(Integer value) {
        return new JAXBElement<Integer>(_Int_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "long")
    public JAXBElement<Long> createLong(Long value) {
        return new JAXBElement<Long>(_Long_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "QName")
    public JAXBElement<QName> createQName(QName value) {
        return new JAXBElement<QName>(_QName_QNAME, QName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "short")
    public JAXBElement<Short> createShort(Short value) {
        return new JAXBElement<Short>(_Short_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedByte")
    public JAXBElement<Short> createUnsignedByte(Short value) {
        return new JAXBElement<Short>(_UnsignedByte_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedInt")
    public JAXBElement<Long> createUnsignedInt(Long value) {
        return new JAXBElement<Long>(_UnsignedInt_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedLong")
    public JAXBElement<BigInteger> createUnsignedLong(BigInteger value) {
        return new JAXBElement<BigInteger>(_UnsignedLong_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "unsignedShort")
    public JAXBElement<Integer> createUnsignedShort(Integer value) {
        return new JAXBElement<Integer>(_UnsignedShort_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "char")
    public JAXBElement<Integer> createChar(Integer value) {
        return new JAXBElement<Integer>(_Char_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/", name = "guid")
    public JAXBElement<String> createGuid(String value) {
        return new JAXBElement<String>(_Guid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnumPayloadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Enums", name = "EnumPayloadType")
    public JAXBElement<EnumPayloadType> createEnumPayloadType(EnumPayloadType value) {
        return new JAXBElement<EnumPayloadType>(_EnumPayloadType_QNAME, EnumPayloadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfstring }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", name = "ArrayOfstring")
    public JAXBElement<ArrayOfstring> createArrayOfstring(ArrayOfstring value) {
        return new JAXBElement<ArrayOfstring>(_ArrayOfstring_QNAME, ArrayOfstring.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "username", scope = AuthenticateUser.class)
    public JAXBElement<String> createAuthenticateUserUsername(String value) {
        return new JAXBElement<String>(_AuthenticateUserUsername_QNAME, String.class, AuthenticateUser.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "password", scope = AuthenticateUser.class)
    public JAXBElement<String> createAuthenticateUserPassword(String value) {
        return new JAXBElement<String>(_AuthenticateUserPassword_QNAME, String.class, AuthenticateUser.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "company", scope = AuthenticateUser.class)
    public JAXBElement<String> createAuthenticateUserCompany(String value) {
        return new JAXBElement<String>(_AuthenticateUserCompany_QNAME, String.class, AuthenticateUser.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = AuthenticateUser.class)
    public JAXBElement<AuthenticationToken> createAuthenticateUserToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, AuthenticateUser.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "AuthenticateUserResult", scope = AuthenticateUserResponse.class)
    public JAXBElement<ArrayOfResult> createAuthenticateUserResponseAuthenticateUserResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_AuthenticateUserResponseAuthenticateUserResult_QNAME, ArrayOfResult.class, AuthenticateUserResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = AuthenticateUserResponse.class)
    public JAXBElement<AuthenticationToken> createAuthenticateUserResponseToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, AuthenticateUserResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = BeginBatch.class)
    public JAXBElement<AuthenticationToken> createBeginBatchToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, BeginBatch.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "batchId", scope = BeginBatch.class)
    public JAXBElement<Long> createBeginBatchBatchId(Long value) {
        return new JAXBElement<Long>(_BeginBatchBatchId_QNAME, Long.class, BeginBatch.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "BeginBatchResult", scope = BeginBatchResponse.class)
    public JAXBElement<ArrayOfResult> createBeginBatchResponseBeginBatchResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_BeginBatchResponseBeginBatchResult_QNAME, ArrayOfResult.class, BeginBatchResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "batchId", scope = BeginBatchResponse.class)
    public JAXBElement<Long> createBeginBatchResponseBatchId(Long value) {
        return new JAXBElement<Long>(_BeginBatchBatchId_QNAME, Long.class, BeginBatchResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = ImportData.class)
    public JAXBElement<AuthenticationToken> createImportDataToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, ImportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Instruction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "importInstruction", scope = ImportData.class)
    public JAXBElement<Instruction> createImportDataImportInstruction(Instruction value) {
        return new JAXBElement<Instruction>(_ImportDataImportInstruction_QNAME, Instruction.class, ImportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "batchId", scope = ImportData.class)
    public JAXBElement<Long> createImportDataBatchId(Long value) {
        return new JAXBElement<Long>(_BeginBatchBatchId_QNAME, Long.class, ImportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ImportDataResult", scope = ImportDataResponse.class)
    public JAXBElement<ArrayOfResult> createImportDataResponseImportDataResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_ImportDataResponseImportDataResult_QNAME, ArrayOfResult.class, ImportDataResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = ExportData.class)
    public JAXBElement<AuthenticationToken> createExportDataToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, ExportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Instruction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "exportInstruction", scope = ExportData.class)
    public JAXBElement<Instruction> createExportDataExportInstruction(Instruction value) {
        return new JAXBElement<Instruction>(_ExportDataExportInstruction_QNAME, Instruction.class, ExportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "batchId", scope = ExportData.class)
    public JAXBElement<Long> createExportDataBatchId(Long value) {
        return new JAXBElement<Long>(_BeginBatchBatchId_QNAME, Long.class, ExportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ExportDataResult", scope = ExportDataResponse.class)
    public JAXBElement<ArrayOfResult> createExportDataResponseExportDataResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_ExportDataResponseExportDataResult_QNAME, ArrayOfResult.class, ExportDataResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Instruction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "exportInstruction", scope = ExportDataResponse.class)
    public JAXBElement<Instruction> createExportDataResponseExportInstruction(Instruction value) {
        return new JAXBElement<Instruction>(_ExportDataExportInstruction_QNAME, Instruction.class, ExportDataResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = ImportExportData.class)
    public JAXBElement<AuthenticationToken> createImportExportDataToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, ImportExportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Instruction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "importExportInstruction", scope = ImportExportData.class)
    public JAXBElement<Instruction> createImportExportDataImportExportInstruction(Instruction value) {
        return new JAXBElement<Instruction>(_ImportExportDataImportExportInstruction_QNAME, Instruction.class, ImportExportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "batchId", scope = ImportExportData.class)
    public JAXBElement<Long> createImportExportDataBatchId(Long value) {
        return new JAXBElement<Long>(_BeginBatchBatchId_QNAME, Long.class, ImportExportData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ImportExportDataResult", scope = ImportExportDataResponse.class)
    public JAXBElement<ArrayOfResult> createImportExportDataResponseImportExportDataResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_ImportExportDataResponseImportExportDataResult_QNAME, ArrayOfResult.class, ImportExportDataResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Instruction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "importExportInstruction", scope = ImportExportDataResponse.class)
    public JAXBElement<Instruction> createImportExportDataResponseImportExportInstruction(Instruction value) {
        return new JAXBElement<Instruction>(_ImportExportDataImportExportInstruction_QNAME, Instruction.class, ImportExportDataResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = EndBatch.class)
    public JAXBElement<AuthenticationToken> createEndBatchToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, EndBatch.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "batchId", scope = EndBatch.class)
    public JAXBElement<Long> createEndBatchBatchId(Long value) {
        return new JAXBElement<Long>(_BeginBatchBatchId_QNAME, Long.class, EndBatch.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "EndBatchResult", scope = EndBatchResponse.class)
    public JAXBElement<ArrayOfResult> createEndBatchResponseEndBatchResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_EndBatchResponseEndBatchResult_QNAME, ArrayOfResult.class, EndBatchResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = GetReceiptSummaryWithBatchID.class)
    public JAXBElement<AuthenticationToken> createGetReceiptSummaryWithBatchIDToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, GetReceiptSummaryWithBatchID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "batchId", scope = GetReceiptSummaryWithBatchID.class)
    public JAXBElement<Long> createGetReceiptSummaryWithBatchIDBatchId(Long value) {
        return new JAXBElement<Long>(_BeginBatchBatchId_QNAME, Long.class, GetReceiptSummaryWithBatchID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "receiptSummary", scope = GetReceiptSummaryWithBatchID.class)
    public JAXBElement<ReceiptSummary> createGetReceiptSummaryWithBatchIDReceiptSummary(ReceiptSummary value) {
        return new JAXBElement<ReceiptSummary>(_GetReceiptSummaryWithBatchIDReceiptSummary_QNAME, ReceiptSummary.class, GetReceiptSummaryWithBatchID.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetReceiptSummaryWithBatchIDResult", scope = GetReceiptSummaryWithBatchIDResponse.class)
    public JAXBElement<ArrayOfResult> createGetReceiptSummaryWithBatchIDResponseGetReceiptSummaryWithBatchIDResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_GetReceiptSummaryWithBatchIDResponseGetReceiptSummaryWithBatchIDResult_QNAME, ArrayOfResult.class, GetReceiptSummaryWithBatchIDResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "receiptSummary", scope = GetReceiptSummaryWithBatchIDResponse.class)
    public JAXBElement<ReceiptSummary> createGetReceiptSummaryWithBatchIDResponseReceiptSummary(ReceiptSummary value) {
        return new JAXBElement<ReceiptSummary>(_GetReceiptSummaryWithBatchIDReceiptSummary_QNAME, ReceiptSummary.class, GetReceiptSummaryWithBatchIDResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = GetReceiptSummaryWithAuditReceipt.class)
    public JAXBElement<AuthenticationToken> createGetReceiptSummaryWithAuditReceiptToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, GetReceiptSummaryWithAuditReceipt.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "receiptSummary", scope = GetReceiptSummaryWithAuditReceipt.class)
    public JAXBElement<ReceiptSummary> createGetReceiptSummaryWithAuditReceiptReceiptSummary(ReceiptSummary value) {
        return new JAXBElement<ReceiptSummary>(_GetReceiptSummaryWithBatchIDReceiptSummary_QNAME, ReceiptSummary.class, GetReceiptSummaryWithAuditReceipt.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetReceiptSummaryWithAuditReceiptResult", scope = GetReceiptSummaryWithAuditReceiptResponse.class)
    public JAXBElement<ArrayOfResult> createGetReceiptSummaryWithAuditReceiptResponseGetReceiptSummaryWithAuditReceiptResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_GetReceiptSummaryWithAuditReceiptResponseGetReceiptSummaryWithAuditReceiptResult_QNAME, ArrayOfResult.class, GetReceiptSummaryWithAuditReceiptResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptSummary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "receiptSummary", scope = GetReceiptSummaryWithAuditReceiptResponse.class)
    public JAXBElement<ReceiptSummary> createGetReceiptSummaryWithAuditReceiptResponseReceiptSummary(ReceiptSummary value) {
        return new JAXBElement<ReceiptSummary>(_GetReceiptSummaryWithBatchIDReceiptSummary_QNAME, ReceiptSummary.class, GetReceiptSummaryWithAuditReceiptResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationToken }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "token", scope = GetReceiptDetails.class)
    public JAXBElement<AuthenticationToken> createGetReceiptDetailsToken(AuthenticationToken value) {
        return new JAXBElement<AuthenticationToken>(_AuthenticateUserToken_QNAME, AuthenticationToken.class, GetReceiptDetails.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfstring }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "rowIdList", scope = GetReceiptDetails.class)
    public JAXBElement<ArrayOfstring> createGetReceiptDetailsRowIdList(ArrayOfstring value) {
        return new JAXBElement<ArrayOfstring>(_GetReceiptDetailsRowIdList_QNAME, ArrayOfstring.class, GetReceiptDetails.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "receiptDetails", scope = GetReceiptDetails.class)
    public JAXBElement<ReceiptDetails> createGetReceiptDetailsReceiptDetails(ReceiptDetails value) {
        return new JAXBElement<ReceiptDetails>(_GetReceiptDetailsReceiptDetails_QNAME, ReceiptDetails.class, GetReceiptDetails.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "GetReceiptDetailsResult", scope = GetReceiptDetailsResponse.class)
    public JAXBElement<ArrayOfResult> createGetReceiptDetailsResponseGetReceiptDetailsResult(ArrayOfResult value) {
        return new JAXBElement<ArrayOfResult>(_GetReceiptDetailsResponseGetReceiptDetailsResult_QNAME, ArrayOfResult.class, GetReceiptDetailsResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiptDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "receiptDetails", scope = GetReceiptDetailsResponse.class)
    public JAXBElement<ReceiptDetails> createGetReceiptDetailsResponseReceiptDetails(ReceiptDetails value) {
        return new JAXBElement<ReceiptDetails>(_GetReceiptDetailsReceiptDetails_QNAME, ReceiptDetails.class, GetReceiptDetailsResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "BatchID", scope = SummaryRowData.class)
    public JAXBElement<Long> createSummaryRowDataBatchID(Long value) {
        return new JAXBElement<Long>(_SummaryRowDataBatchID_QNAME, Long.class, SummaryRowData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "ExtraErrorDetails", scope = SummaryRowData.class)
    public JAXBElement<String> createSummaryRowDataExtraErrorDetails(String value) {
        return new JAXBElement<String>(_SummaryRowDataExtraErrorDetails_QNAME, String.class, SummaryRowData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "RowID", scope = SummaryRowData.class)
    public JAXBElement<String> createSummaryRowDataRowID(String value) {
        return new JAXBElement<String>(_SummaryRowDataRowID_QNAME, String.class, SummaryRowData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Instruction", scope = Result.class)
    public JAXBElement<String> createResultInstruction(String value) {
        return new JAXBElement<String>(_Instruction_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Message", scope = Result.class)
    public JAXBElement<String> createResultMessage(String value) {
        return new JAXBElement<String>(_ResultMessage_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Severity", scope = Result.class)
    public JAXBElement<String> createResultSeverity(String value) {
        return new JAXBElement<String>(_ResultSeverity_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "StatusCode", scope = Result.class)
    public JAXBElement<String> createResultStatusCode(String value) {
        return new JAXBElement<String>(_ResultStatusCode_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "ResultDetails", scope = ReceiptDetails.class)
    public JAXBElement<String> createReceiptDetailsResultDetails(String value) {
        return new JAXBElement<String>(_ReceiptDetailsResultDetails_QNAME, String.class, ReceiptDetails.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfSummaryRowData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "RowDataItems", scope = ReceiptSummary.class)
    public JAXBElement<ArrayOfSummaryRowData> createReceiptSummaryRowDataItems(ArrayOfSummaryRowData value) {
        return new JAXBElement<ArrayOfSummaryRowData>(_ReceiptSummaryRowDataItems_QNAME, ArrayOfSummaryRowData.class, ReceiptSummary.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Directive", scope = Instruction.class)
    public JAXBElement<String> createInstructionDirective(String value) {
        return new JAXBElement<String>(_InstructionDirective_QNAME, String.class, Instruction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Payload", scope = Instruction.class)
    public JAXBElement<String> createInstructionPayload(String value) {
        return new JAXBElement<String>(_InstructionPayload_QNAME, String.class, Instruction.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "BLL", scope = AuthenticationToken.class)
    public JAXBElement<String> createAuthenticationTokenBLL(String value) {
        return new JAXBElement<String>(_AuthenticationTokenBLL_QNAME, String.class, AuthenticationToken.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Company", scope = AuthenticationToken.class)
    public JAXBElement<String> createAuthenticationTokenCompany(String value) {
        return new JAXBElement<String>(_AuthenticationTokenCompany_QNAME, String.class, AuthenticationToken.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "DAL", scope = AuthenticationToken.class)
    public JAXBElement<String> createAuthenticationTokenDAL(String value) {
        return new JAXBElement<String>(_AuthenticationTokenDAL_QNAME, String.class, AuthenticationToken.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", name = "Session", scope = AuthenticationToken.class)
    public JAXBElement<String> createAuthenticationTokenSession(String value) {
        return new JAXBElement<String>(_AuthenticationTokenSession_QNAME, String.class, AuthenticationToken.class, value);
    }

}
