//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.28 at 02:19:50 PM IST 
//


package com.concretepage.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SummaryRowData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SummaryRowData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AuditReceipt" type="{http://schemas.microsoft.com/2003/10/Serialization/}guid" minOccurs="0"/&gt;
 *         &lt;element name="BatchID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ExtraErrorDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RowID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="StatusCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SummaryRowData", namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", propOrder = {
    "auditReceipt",
    "batchID",
    "extraErrorDetails",
    "rowID",
    "severity",
    "statusCode"
})
public class SummaryRowData {

    @XmlElement(name = "AuditReceipt")
    protected String auditReceipt;
    @XmlElementRef(name = "BatchID", namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> batchID;
    @XmlElementRef(name = "ExtraErrorDetails", namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", type = JAXBElement.class, required = false)
    protected JAXBElement<String> extraErrorDetails;
    @XmlElementRef(name = "RowID", namespace = "http://schemas.datacontract.org/2004/07/JustEnough.API.ImportExport.Objects.Model", type = JAXBElement.class, required = false)
    protected JAXBElement<String> rowID;
    @XmlElement(name = "Severity")
    protected Integer severity;
    @XmlElement(name = "StatusCode")
    protected Integer statusCode;

    /**
     * Gets the value of the auditReceipt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditReceipt() {
        return auditReceipt;
    }

    /**
     * Sets the value of the auditReceipt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditReceipt(String value) {
        this.auditReceipt = value;
    }

    /**
     * Gets the value of the batchID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getBatchID() {
        return batchID;
    }

    /**
     * Sets the value of the batchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setBatchID(JAXBElement<Long> value) {
        this.batchID = value;
    }

    /**
     * Gets the value of the extraErrorDetails property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getExtraErrorDetails() {
        return extraErrorDetails;
    }

    /**
     * Sets the value of the extraErrorDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setExtraErrorDetails(JAXBElement<String> value) {
        this.extraErrorDetails = value;
    }

    /**
     * Gets the value of the rowID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRowID() {
        return rowID;
    }

    /**
     * Sets the value of the rowID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRowID(JAXBElement<String> value) {
        this.rowID = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeverity(Integer value) {
        this.severity = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStatusCode(Integer value) {
        this.statusCode = value;
    }

}
